# Generated by Django 5.2.17 on 2026-09-03 18:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='n° ticket')),
                ('status', models.CharField(choices=[('RECU', 'Reçu'), ('EN_TRAITEMENT', 'En traitement'), ('PRET', 'Prêt'), ('LIVRE', 'Livré')], default='RECU', max_length=20, verbose_name='statut')),
                ('canal', models.CharField(choices=[('COMPTOIR', 'Comptoir'), ('EN_LIGNE', 'En ligne')], default='COMPTOIR', max_length=10, verbose_name='canal')),
                ('date_depot', models.DateTimeField(verbose_name='date de dépôt')),
                ('date_retrait_prevue', models.DateTimeField(verbose_name='date de retrait prévue')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='montant total')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='clients.client', verbose_name='client')),
                ('pressing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='tenants.pressing', verbose_name='pressing')),
            ],
            options={
                'verbose_name': 'commande',
                'ordering': ['-date_depot'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clothing_type', models.CharField(max_length=100, verbose_name='type de vêtement')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix unitaire')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='orders.commande', verbose_name='commande')),
            ],
            options={
                'verbose_name': 'article de commande',
                'verbose_name_plural': 'articles de commande',
            },
        ),
    ]
