# Generated by Django 5.2.17 on 2026-09-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='n° ticket'),
        ),
        migrations.AddConstraint(
            model_name='commande',
            constraint=models.UniqueConstraint(fields=('pressing', 'ticket_number'), name='unique_ticket_per_pressing'),
        ),
    ]
