# Generated by Django 5.2.17 on 2026-09-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_commande_ticket_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='payment_status',
            field=models.CharField(choices=[('PAYE', 'Payé'), ('PARTIEL', 'Partiel'), ('CREDIT', 'Crédit')], default='CREDIT', max_length=10, verbose_name='statut paiement'),
        ),
    ]
