# Generated by Django 5.2.17 on 2026-09-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_commande_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_pret',
            field=models.DateTimeField(blank=True, null=True, verbose_name='passé prêt le'),
        ),
    ]
