# Generated by Django 5.2.17 on 2026-09-03 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        ('orders', '0004_commande_date_pret'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='assigned_courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='deliveries.courier', verbose_name='coursier assigné'),
        ),
        migrations.AddField(
            model_name='commande',
            name='collect_address',
            field=models.TextField(blank=True, default='', verbose_name='adresse de collecte'),
        ),
        migrations.AddField(
            model_name='commande',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('A_COLLECTER', 'À collecter'), ('COLLECTE', 'Collecté'), ('A_LIVRER', 'À livrer'), ('LIVRE', 'Livré')], max_length=15, null=True, verbose_name='statut de livraison'),
        ),
    ]
