# Generated by Django 5.2.17 on 2026-09-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('GERANT', 'Gérant'), ('EMPLOYE', 'Employé'), ('COURSIER', 'Coursier')], default='EMPLOYE', max_length=16, verbose_name='rôle'),
        ),
    ]
