# Generated by Django 5.2.17 on 2026-09-03 09:52

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pressing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('address', models.TextField(blank=True, verbose_name='adresse')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='téléphone')),
                ('owner_name', models.CharField(blank=True, max_length=255, verbose_name='propriétaire')),
                ('logo', models.ImageField(blank=True, upload_to='tenants/logos/', verbose_name='logo')),
                ('primary_color', models.CharField(default='#1E90FF', max_length=7, validators=[django.core.validators.RegexValidator(message='Le champ doit être un code couleur hexadécimal (ex. #1E90FF).', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='couleur primaire')),
                ('secondary_color', models.CharField(default='#FF8C00', max_length=7, validators=[django.core.validators.RegexValidator(message='Le champ doit être un code couleur hexadécimal (ex. #1E90FF).', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='couleur secondaire')),
            ],
            options={
                'verbose_name': 'pressing',
                'verbose_name_plural': 'pressings',
                'ordering': ['-created_at'],
            },
        ),
    ]
