# Generated by Django 5.2.17 on 2026-09-03 19:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_commande_payment_status'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='montant encaissé')),
                ('mode', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('CREDIT', 'Crédit')], default='ESPECES', max_length=15, verbose_name='mode')),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de paiement')),
                ('status', models.CharField(choices=[('PAYE', 'Payé'), ('PARTIEL', 'Partiel'), ('CREDIT', 'Crédit')], max_length=10, verbose_name='statut')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='orders.commande', verbose_name='commande')),
                ('pressing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='tenants.pressing', verbose_name='pressing')),
            ],
            options={
                'verbose_name': 'paiement',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
