# Generated by Django 5.2.17 on 2026-09-03 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('phone_number', models.CharField(max_length=32, verbose_name='téléphone')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('pressing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='tenants.pressing', verbose_name='pressing')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_profile', to=settings.AUTH_USER_MODEL, verbose_name='compte de connexion')),
            ],
            options={
                'verbose_name': 'coursier',
                'verbose_name_plural': 'coursiers',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('phone_number', 'pressing'), name='unique_courier_phone_per_pressing')],
            },
        ),
    ]
