# Generated by Django 5.2.17 on 2026-09-03 18:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('phone_number', models.CharField(max_length=32, verbose_name='téléphone')),
                ('pressing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='tenants.pressing', verbose_name='pressing')),
            ],
            options={
                'verbose_name': 'client',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('phone_number', 'pressing'), name='unique_client_phone_per_pressing')],
            },
        ),
    ]
