# Generated by Django 5.2.17 on 2026-09-03 19:19

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_commande_payment_status'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.CharField(choices=[('ORANGE', 'Orange Money'), ('MOOV', 'Moov Money')], max_length=10, verbose_name='opérateur')),
                ('phone_number', models.CharField(max_length=32, verbose_name='téléphone payeur')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant demandé')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('FAILED', 'Échouée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=10, verbose_name='statut')),
                ('provider_ref', models.CharField(blank=True, default='', max_length=64, verbose_name='référence opérateur')),
                ('error_message', models.TextField(blank=True, default='', verbose_name="message d'erreur")),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobile_money_requests', to='orders.commande', verbose_name='commande')),
                ('pressing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_requests', to='tenants.pressing', verbose_name='pressing')),
            ],
            options={
                'verbose_name': 'demande Mobile Money',
                'verbose_name_plural': 'demandes Mobile Money',
                'ordering': ['-created_at'],
            },
        ),
    ]
