# Generated by Django 5.2.17 on 2026-09-03 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_commande_date_pret'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('READY', 'Linge prêt'), ('REMINDER', 'Relance oubli')], max_length=10, verbose_name='type')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('SIMULATED', 'Simulé (passerelle non configurée)'), ('FAILED', 'Échec')], default='PENDING', max_length=10, verbose_name='statut')),
                ('phone_number', models.CharField(max_length=32, verbose_name='destinataire')),
                ('message', models.TextField(verbose_name='message')),
                ('provider_ref', models.CharField(blank=True, default='', max_length=64, verbose_name='référence passerelle')),
                ('error_message', models.TextField(blank=True, default='', verbose_name="message d'erreur")),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sms_notifications', to='orders.commande', verbose_name='commande')),
                ('pressing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='tenants.pressing', verbose_name='pressing')),
            ],
            options={
                'verbose_name': 'notification SMS',
                'verbose_name_plural': 'notifications SMS',
                'ordering': ['-created_at'],
            },
        ),
    ]
